-- Plantilla global Header y Footer 02 (logo centrado + barra naranja)
-- Ejecutar en Supabase SQL Editor despues de 008_frame_hf01_typography.sql

INSERT INTO brand_frame_templates (
  branch_id,
  name,
  description,
  is_default,
  is_active,
  layout_version,
  header_style,
  header_show_logo,
  header_corner_size,
  footer_whatsapp_display,
  footer_website_display,
  footer_cta_text,
  footer_show_whatsapp,
  footer_show_website,
  footer_show_cta,
  footer_show_footer_logo,
  footer_height,
  footer_adaptive_color,
  footer_font_family,
  footer_whatsapp_font_size,
  footer_website_font_size,
  footer_cta_font_size,
  footer_icon_size,
  footer_whatsapp_text_color,
  footer_website_text_color,
  accent_color,
  footer_bg_color,
  cta_bg_color,
  cta_text_color,
  whatsapp_icon_color,
  website_icon_color,
  text_color
)
SELECT
  NULL,
  'Header y Footer 02',
  'Logo centrado arriba, barra naranja inferior, boton ORDENA AHORA y contacto web/telefono',
  false,
  true,
  'hf02',
  'minimal',
  true,
  300,
  '+56 9 8692 5310',
  'www.el-pollon.cl',
  'ORDENA AHORA!',
  true,
  true,
  true,
  false,
  130,
  true,
  'Roboto-Black',
  26,
  26,
  24,
  44,
  '#000000',
  '#000000',
  '#c50000',
  '#F59E0B',
  '#c50000',
  '#ffffff',
  '#c50000',
  '#c50000',
  '#000000'
WHERE NOT EXISTS (
  SELECT 1 FROM brand_frame_templates
  WHERE branch_id IS NULL AND layout_version = 'hf02'
);
